db/schema.sql

I added anime_db to the db- schema.sql file.

added database called anime_db in schema.sql file

---

controllers/home-routes.js
controllers/index.js
server.js

Created the homepage route file: 
linked it up with controller index: 
go to http://[localhost:3001](http://localhost:3001/)/ after starting the server, the roote path should display this:

created homepage route

---

controllers/index.js
controllers/searchResult-routes.js

go to http://[localhost:3001/search](http://localhost:3001/search) and you should see:

added search results route

---

.github/PULL_REQUEST_TEMPLATE.md

added a pull request template so we can explain what we in our code

---

.env.EXAMPLE

Added an .env.EXAMPLE file
Fixes #21 
- path/to/file
- .env.EXAMPLE

create environment example file

---

models/User.js

I created a user.js file for the model where i added the checking of the password, user init, hook and exporting the user. :)
Fixes #27
- path/to/file
- models/User.js

27 user model

---

views/layouts/main.handlebars

Fixes #41
- path/to/file
- start server
- got to any route and see the navbar

41 create header for main handlebar layout

---

models/Anime.js

Added the anime info in the js file for the model it includes the id, title description, user id and api id when we are ready to get the api info
Fixes #42 
- path/to/file
- models/Anime.js

42 anime model check api to gather fields

---

models/index.js

Created the link between anime and user so user can have multiple anime.
Fixes #43 
- path/to/file
- models/index.js

added the realtionship between user and anime in index.js file

---

.github/PULL_REQUEST_TEMPLATE.md
views/layouts/main.handlebars

i changed the title in the main handlebars, i also added our title in the nav bar, i also fixed the spelling error in the pull request template
Fixes #48 
- path/to/file
- .github/PULL_REQUEST_TEMPLATE.md

48 title for main handlebars and fixing typo error for pull request template

---

seeds/animeData.json

add manual data for anime table
Fixes #28 
- path/to/file
- seeds/animeData.json

seed anime data

---

seeds/userData.json

add manual data to for users
Fixes #26 
- path/to/file
- seeds/userData.json

seed user data

---

seeds/seed.js

bulk create user data and anime data.
Fixes #25 
- path/to/file
- seeds/seed.js

create seed data

---

views/category.handlebars
views/followed.handlebars
views/searchResults.handlebars

created the following files as a placeholder to be worked on.
Fixes #62 
- path/to/file
- views/category.handlebars
- views/followed.handlebars
- views/searchResults.handlebars

62 initiate the handlebars

---

public/js/login.js
public/js/logout.js
public/js/signup.js
utils/auth.js

create login js files and 2 new folders
Fixes #[issue]
- public/js/login.js
- public/js/logout.js
- public/js/signup.js
- utils/auth.js
- look at public folder
- look at utils folder

55 create login

---

controllers/searchResult-routes.js
views/partials/animeCard.handlebars
views/searchResults.handlebars

Fixes #67 
- path/to/file
- controllers/searchResult-routes.js
- views/partials/animeCard.handlebars
- views/searchResults.handlebars
- start the server
- go to http://localhost:3001/search?q=naruto and you should see this:

67 create search results route and page

---

package-lock.json
package.json
public/css/style.css
server.js
views/homepage.handlebars
views/layouts/main.handlebars

Fixes #63 
- path/to/file
- package-lock.json
- package.json
- server.js
- views/homepage.handlebars
- use "npm i" in terminal
- start the node server using "npm start"
- enter http://localhost:3001 into your browser and you should see the following:
https://gyazo.com/6991234163954750da0c8865f80e5054

63 style card for homepagehandlebars

---

views/layouts/main.handlebars

adds logout button when logged in
Fixes #[issue]
small.

added logout button

---

public/css/style.css
views/partials/animeCard.handlebars
views/searchResults.handlebars

Fixes #79 
- path/to/file
- public/css/style.css
- views/partials/animeCard.handlebars
- views/searchResults.handlebars
- start server
- go to http://localhost:3001/search?q=naruto

styled cards in the search results page

---

public/css/style.css
public/js/search.js
views/layouts/main.handlebars
views/partials/animeCard.handlebars
views/searchResults.handlebars

Fixes #81 
- path/to/file
- public/css/style.css
- public/js/search.js
- views/partials/animeCard.handlebars
- views/searchResults.handlebars
- start server
- search something in the search bar
- click the search button
- should be show search results

81 link up search bar to search results page

---

controllers/searchResult-routes.js
public/css/style.css
public/js/search.js
views/layouts/main.handlebars
views/partials/animeCard.handlebars
views/searchResults.handlebars

Fixes #83 
- path/to/file
- controllers/searchResult-routes.js
- also some other ones from previous branches, once they're all pushed in should be fine
- start server
- search for anything and they should have all have a rating

83 query search results in the backend to only show valid anime data

---

controllers/api/index.js
controllers/api/loginRoutes.js

- created login router
- added login router to api path
Fixes #72 
- path/to/file
- controllers/api/loginRoutes.js

72 login api route

---

controllers/api/index.js
controllers/api/loginRoutes.js
controllers/api/signupRoutes.js
package-lock.json
package.json

created sign up route and added it to api route
Fixes #74 
- path/to/file
- controllers/api/signupRoutes.js
- change

74 sign up api route

---

models/Anime.js
models/User.js
seeds/seed.js

- updated DateTypes to TEXT to hold more than 255 character. 
- added 's' to DataType in import.
- updated Anime bulkCreate 
- added UserAnime bulkCreate
Fixes #22
- path/to/file
- models/Anime.js
- models/User.js
- seeds/seed.js

22 create seeds

---

views/login.handlebars

Fixes #89 
- path/to/file
- views/login.handlebars
- start server
- go to http://localhost:3001/signup

changed signup to login for the legend

---

controllers/api/index.js
controllers/api/logoutRoutes.js

added the router.use and const logout to index.js and added the logoutroutes to the api folder. 
Fixes #73 
- path/to/file
-controllers/api/logoutRoutes.js

73 logout api route

---

public/css/style.css
views/layouts/main.handlebars

got rid of the nav in navbar for the title
Fixes #93 
- path/to/file

got rid of nav in navbar title

---

views/login.handlebars

added required to user and password
Fixes #100 
- path/to/file
-views/login.handlebars

added required to the username and password

---

public/css/carousel.css
public/js/carousel.js
views/example.card.html
views/homepage.handlebars
views/layouts/main.handlebars

Fixes #103 
- path/to/file
- public/css/carousel.css
- public/js/carousel.js
- views/example.card.html
- views/homepage.handlebars
- start server
- go to http://localhost:3001/ try the buttons, they should work

103 add carousel to homepage top 10 list

---

controllers/api/loginRoutes.js
models/User.js
models/UserAnime.js
seeds/seed.js
seeds/userData.json

made changes to models and seeds
Fixes #105 
- path/to/file
- controllers/api/loginRoutes.js
- models/User.js
- models/UserAnime.js
- seeds/seed.js
- seeds/userData.json

105 update user model

---

controllers/api/index.js
controllers/api/loginRoutes.js
controllers/home-routes.js
controllers/searchResult-routes.js
controllers/signup-routes.js
models/User.js
public/js/login.js
public/js/logout.js
seeds/userData.json
views/layouts/main.handlebars

- fixed api path and passed logged_in. 
- refactored database field from name to username. 
- fixed variable used in if statement block.
Fixes #111 
- path/to/file
- controllers/api/loginRoutes.js
- controllers/home-routes.js
- controllers/searchResult-routes.js
- controllers/signup-routes.js
- models/User.js
- public/js/login.js
- public/js/logout.js
- seeds/userData.json

111 refactor database field name

---

controllers/api/followRoutes.js
controllers/api/index.js
models/Anime.js
models/UserAnime.js
public/js/follow.js
seeds/animeData.json
seeds/seed.js
views/layouts/main.handlebars
views/partials/animeCard.handlebars

Fixes #110 
- path/to/file
- controllers/api/followRoutes.js
- models/Anime.js
- models/UserAnime.js
- public/js/follow.js
- public/js/follow.js
- seeds/animeData.json
- seeds/seed.js
- views/partials/animeCard.handlebars
- start server
- search for an anime
- click follow on any anime
- look at the database and and select useranime table
- you should see extra rows, more than 3 rows …

110 create feature for following animes

---

controllers/api/followRoutes.js
controllers/followed-routes.js
controllers/searchResult-routes.js
models/Anime.js
seeds/animeData.json
views/followed.handlebars
views/partials/animeCard.handlebars

Fixes #119 
- path/to/file
- controllers/api/followRoutes.js
- change
- change

user can save favorited anime and view them on the follows page

---

views/animeDetails.handlebars

Fixes #135 
- path/to/file
- views/animeDetails.handlebars
- change
- change

created a handlebars page for anime details

---

public/css/style.css
views/followed.handlebars

makes all cards on follow page into 3in a row
Fixes #124 
- views/followed.handlebars
- change
- change
- change
- open site 
- click on follow after login

124 follow list

---

controllers/animeDetails-routes.js
controllers/index.js

Fixes #133 
- path/to/file
- controllers/index.js
- controllers/animeDetails-routes.js
- check the altered files for errors (The route isn't finished yet finishing it in the next issue)

create express route to handle anime details

---

public/js/login.js

- added .value to document query. 
- user was unable to login because of incorrect function. 
Fixes #145
- path/to/file
- public/js/login.js

add .value to document query

---

controllers/followed-routes.js
utils/auth.js
views/homepage.handlebars

- uncommented withAuth in utils folder.
- imported and implemented withAuth in followed route
Fixes #128
- path/to/file
- controllers/followed-routes.js
- utils/auth.js
- views/homepage.handlebars

128 redirect user to sign in page when user goes to disallowed routes

---

controllers/animeDetails-routes.js

Fixes #137 
- path/to/file
- controllers/animeDetails-routes.js
- start server
- go to localhost:3001/details/20
- see if you get data in the console

Changed route to give us details for an anime based on and id provided

---

public/css/carousel.css
public/css/style.css
views/example.card.html

Just fixed up the code in css folder
Fixes #126 
- path/to/file
- public/css/carousel.css
-public/css/style.css
- views/example.card.html

126 clean up css file to remove unused class styles

---

controllers/animeDetails-routes.js
public/css/anime-details.css
public/css/style.css
views/animeDetails.handlebars
views/example.card.html
views/layouts/main.handlebars
views/partials/animeCard.handlebars
views/partials/animeCardLoggedIn.handlebars

Fixes #139 
- path/to/file
- change
- change
- change

139 optional style the page in this ticket or create a new one afterwards

---

public/css/anime-details.css

Fixes #155 
just added a root fixed it up a bit
- path/to/file
- public/css/anime-details.css

added root to anime css

---

views/partials/animeCard.handlebars
views/partials/animeCardLoggedIn.handlebars
views/partials/topTenCard.handlebars

Fixes #154 
- path/to/file
- change
- change
- change

154 link all cards in the application to the details page

---

views/partials/topTenCard.handlebars

- add if statement in partial by using {{# if @root.logged_in}}
Fixes #130 
- path/to/file
- views/partials/topTenCard.handlebars

display follow button if user is logged in

---

public/css/style.css

just added text-decoration none for links
Fixes #161 
- path/to/file
- public/css/style.css

added text decoration none for a tags

---

views/animeDetails.handlebars

Fixes #164 
- path/to/file
- views/animeDetails.handlebars
- start server
- log in or sign up
- go to any details page
- click follow
- go to follows page
- the anime should show up there

follow button on details page now works

---

README.md

Fixes #168 
- path/to/file
- README.md

168 add to readme
